---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus-deployment
  labels:
    app: janus-app
    tier: web-rtc
spec:
  template:
    metadata:
      name: janus-pods
      labels:
        app: janus-app
        tier: web-rtc
    spec:
      containers:
        - name: janus-containers
          image: ghcr.io/meetecho/janus-gateway-docker:latest
  replicas: 2
  selector:
    matchLabels:
      app: janus-app
      tier: web-rtc
...

