...
apiVersion: v1
kind: Service
metadata:
  name: janus-service

spec:
  type: NodePort
  ports:
   - port: 8188
     targetPort: 8188
   - port: 8088
     targetPort: 8088
   - port: 8089
     targetPort: 8089
   - port: 8189
     targetPort: 8189
   - port: 7088
     targetPort: 7088
   - port: 7089
     targetPort: 7089
  selector:
    app: janus-app
